gray.http.header.keys = x-apikey
gray.http.parameter.keys = apiKey
hystrix.command.bmw-om-event-uat.execution.isolation.thread.timeoutInMilliseconds = 6000
hystrix.command.bmw-om-uat.execution.isolation.thread.timeoutInMilliseconds = 6000
hystrix.command.cr-mapping-23plus.execution.isolation.thread.timeoutInMilliseconds = 6000
hystrix.command.cr-mapping-daimler.execution.isolation.thread.timeoutInMilliseconds = 6000
hystrix.command.cr-mapping-level2.execution.isolation.thread.timeoutInMilliseconds = 6000
hystrix.command.cr-mapping.execution.isolation.thread.timeoutInMilliseconds = 6000
hystrix.command.crp-routing.execution.isolation.thread.timeoutInMilliseconds = 60000
hystrix.command.default.circuitBreaker.requestVolumeThreshold = 10000
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds = 10000
hystrix.command.drive-test.execution.isolation.thread.timeoutInMilliseconds = 60000
hystrix.command.event-23m.execution.isolation.thread.timeoutInMilliseconds = 6000
hystrix.command.event-23plus.execution.isolation.thread.timeoutInMilliseconds = 6000
hystrix.command.fowardRoute.execution.isolation.thread.timeoutInMilliseconds = 60000
hystrix.command.line-search-2023.execution.isolation.thread.timeoutInMilliseconds = 10000
hystrix.command.rgeo-service.execution.isolation.thread.timeoutInMilliseconds = 3000
hystrix.command.route-range-map-25m-uat.execution.isolation.thread.timeoutInMilliseconds = 120000
hystrix.command.routing-services-25m-uat.execution.isolation.thread.timeoutInMilliseconds = 60000
hystrix.command.routing-services-uat-25mm.execution.isolation.thread.timeoutInMilliseconds = 10000
hystrix.command.routing-services-uat.execution.isolation.thread.timeoutInMilliseconds = 30000
hystrix.command.search2021-uat.execution.isolation.thread.timeoutInMilliseconds = 10000
hystrix.command.search2022-uat.execution.isolation.thread.timeoutInMilliseconds = 10000
hystrix.command.tmc-23m.execution.isolation.thread.timeoutInMilliseconds = 6000
hystrix.command.tmc-23plus.execution.isolation.thread.timeoutInMilliseconds = 6000
hystrix.command.topic-services-2023.execution.isolation.thread.timeoutInMilliseconds = 6000
hystrix.command.topic-services.execution.isolation.thread.timeoutInMilliseconds = 6000
hystrix.threadpool.bmw-om-event-uat.coreSize = 50
hystrix.threadpool.bmw-om-event-uat.maxQueueSize = 10000
hystrix.threadpool.bmw-om-event-uat.queueSizeRejectionThreshold = 3000
hystrix.threadpool.bmw-om-uat.coreSize = 50
hystrix.threadpool.bmw-om-uat.maxQueueSize = 10000
hystrix.threadpool.bmw-om-uat.queueSizeRejectionThreshold = 3000
hystrix.threadpool.cr-mapping-23plus.coreSize = 50
hystrix.threadpool.cr-mapping-23plus.maxQueueSize = 10000
hystrix.threadpool.cr-mapping-23plus.queueSizeRejectionThreshold = 6000
hystrix.threadpool.cr-mapping-daimler.coreSize = 50
hystrix.threadpool.cr-mapping-daimler.maxQueueSize = 10000
hystrix.threadpool.cr-mapping-daimler.queueSizeRejectionThreshold = 6000
hystrix.threadpool.cr-mapping-level2.coreSize = 50
hystrix.threadpool.cr-mapping-level2.maxQueueSize = 10000
hystrix.threadpool.cr-mapping-level2.queueSizeRejectionThreshold = 6000
hystrix.threadpool.cr-mapping.coreSize = 50
hystrix.threadpool.cr-mapping.maxQueueSize = 10000
hystrix.threadpool.cr-mapping.queueSizeRejectionThreshold = 6000
hystrix.threadpool.crp-routing.coreSize = 50
hystrix.threadpool.crp-routing.maxQueueSize = 10000
hystrix.threadpool.crp-routing.queueSizeRejectionThreshold = 3000
hystrix.threadpool.drive-test.coreSize = 20
hystrix.threadpool.drive-test.maxQueueSize = 10000
hystrix.threadpool.drive-test.queueSizeRejectionThreshold = 60000
hystrix.threadpool.event-23m.coreSize = 50
hystrix.threadpool.event-23m.maxQueueSize = 10000
hystrix.threadpool.event-23m.queueSizeRejectionThreshold = 3000
hystrix.threadpool.event-23plus.coreSize = 50
hystrix.threadpool.event-23plus.maxQueueSize = 10000
hystrix.threadpool.event-23plus.queueSizeRejectionThreshold = 3000
hystrix.threadpool.fowardRoute.coreSize = 3000
hystrix.threadpool.fowardRoute.maxQueueSize = 10000
hystrix.threadpool.fowardRoute.queueSizeRejectionThreshold = 10000
hystrix.threadpool.line-search-2023.coreSize = 50
hystrix.threadpool.line-search-2023.maxQueueSize = 10000
hystrix.threadpool.line-search-2023.queueSizeRejectionThreshold = 3000
hystrix.threadpool.rgeo-service.coreSize = 10
hystrix.threadpool.rgeo-service.maxQueueSize = 10000
hystrix.threadpool.rgeo-service.queueSizeRejectionThreshold = 5000
hystrix.threadpool.route-range-map-25m-uat.coreSize = 50
hystrix.threadpool.route-range-map-25m-uat.maxQueueSize = 10000
hystrix.threadpool.route-range-map-25m-uat.queueSizeRejectionThreshold = 10000
hystrix.threadpool.routing-services-25m-uat.coreSize = 150
hystrix.threadpool.routing-services-25m-uat.maxQueueSize = 10000
hystrix.threadpool.routing-services-25m-uat.queueSizeRejectionThreshold = 10000
hystrix.threadpool.routing-services-uat-25mm.coreSize = 150
hystrix.threadpool.routing-services-uat-25mm.maxQueueSize = 10000
hystrix.threadpool.routing-services-uat-25mm.queueSizeRejectionThreshold = 10000
hystrix.threadpool.routing-services-uat.coreSize = 150
hystrix.threadpool.routing-services-uat.maxQueueSize = 10000
hystrix.threadpool.routing-services-uat.queueSizeRejectionThreshold = 10000
hystrix.threadpool.search2021-uat.coreSize = 50
hystrix.threadpool.search2021-uat.maxQueueSize = 10000
hystrix.threadpool.search2021-uat.queueSizeRejectionThreshold = 3000
hystrix.threadpool.search2022-uat.coreSize = 50
hystrix.threadpool.search2022-uat.maxQueueSize = 10000
hystrix.threadpool.search2022-uat.queueSizeRejectionThreshold = 3000
hystrix.threadpool.tmc-23m.coreSize = 50
hystrix.threadpool.tmc-23m.maxQueueSize = 10000
hystrix.threadpool.tmc-23m.queueSizeRejectionThreshold = 3000
hystrix.threadpool.tmc-23plus.coreSize = 50
hystrix.threadpool.tmc-23plus.maxQueueSize = 10000
hystrix.threadpool.tmc-23plus.queueSizeRejectionThreshold = 3000
hystrix.threadpool.topic-services-2023.coreSize = 50
hystrix.threadpool.topic-services-2023.maxQueueSize = 10000
hystrix.threadpool.topic-services-2023.queueSizeRejectionThreshold = 3000
hystrix.threadpool.topic-services.coreSize = 50
hystrix.threadpool.topic-services.maxQueueSize = 10000
hystrix.threadpool.topic-services.queueSizeRejectionThreshold = 3000
info.name = wecloud-openapi-gateway-new
logback.access.config = config/logback-access.xml
logback.access.enabled = true
logback.access.useServerPortInsteadOfLocalPort = true
logging.config = config/logback-spring.xml
management.health.redis.enabled = false
multipart.enabled = true
multipart.max-file-size = 51MB
multipart.max-request-size = 51MB
ribbon.ConnectTimeout = 120000
ribbon.MaxAutoRetriesNextServer = 1
ribbon.MaxConnectionsPerHost = 5000
ribbon.MaxTotalConnections = 10000
ribbon.OkToRetryOnAllOperations = true
ribbon.ReadTimeout = 120000
server.tomcat.accept-count = 5000
server.tomcat.connection-timeout = 120000
server.tomcat.max-connections = 20000
server.tomcat.max-threads = 2000
server.tomcat.uri-encoding = UTF-8
spring.cloud.loadbalancer.retry.enabled = true
spring.cloud.stream.bindings.springCloudBusInput.group = ${spring.application.name}.${spring.cloud.client.ipAddress}
spring.cloud.stream.kafka.binder.brokers = localhost
spring.cloud.stream.kafka.binder.defaultBrokerPort = 9092
spring.cloud.stream.kafka.binder.defaultZkPort = 2181
spring.cloud.stream.kafka.binder.zkNodes = localhost
spring.http.multipart.enabled = true
spring.http.multipart.max-file-size = 50MB
spring.http.multipart.max-request-size = 51MB
spring.redis.host = localhost
spring.redis.pool.max-active = 2000
spring.redis.pool.max-idle = 100
spring.redis.pool.max-wait = -1
spring.redis.pool.min-idle = 50
spring.redis.port = 6379
spring.redis.timeout = 0
spring.sleuth.sampler.percentage = 0.01
toyota.authentication.chechKey = mnvwijxk
toyota.authentication.url = https://test-ecmapshop.autoai.com/mapdataShop/licenseToyota/toyota617.do
toyota.checkUri = /router/p1/routing
wecloud.auth.excludeUrl = /tuhu/p1/orderNotify,/ssoapi/**,/music/gw/m,/music/gw/t,/search-test/search/v1/config
wecloud.auth.whitelist = {\"a944bb3a4ae04ab68a3609eee54e3801\":\"60.16.1.36,118.244.200.102\"}
wecloud.gateway.filter.crossEnabled = true
wecloud.gateway.gray.type = common
wecloud.gray.enabled = true
zuul.host.connect-timeout-millis = 120000
zuul.host.maxPerRouteConnections = 5000
zuul.host.maxTotalConnections = 10000
zuul.host.socket-timeout-millis = 120000
zuul.host.time-to-live = 5000
zuul.include-debug-header = true
zuul.ribbonIsolationStrategy = THREAD
zuul.routes.bmw-om-event-uat.path = /bmw-om-uat/event/**
zuul.routes.bmw-om-event-uat.url = http://192.168.101.204:8094/event/
zuul.routes.bmw-om-uat.path = /bmw-om-uat/**
zuul.routes.bmw-om-uat.url = http://192.168.101.204:8084/
zuul.routes.cr-mapping-23plus.path = /cr-mapping-23plus/**
zuul.routes.cr-mapping-23plus.url = http://192.168.101.60/cr-mapping-23plus/
zuul.routes.cr-mapping-daimler.path = /cr-mapping-daimler/**
zuul.routes.cr-mapping-daimler.url = http://192.168.101.60/cr-mapping-daimler/
zuul.routes.cr-mapping-level2.path = /cr-mapping-level2/**
zuul.routes.cr-mapping-level2.url = http://192.168.101.60/cr-mapping-level2/
zuul.routes.cr-mapping.path = /cr-mapping/**
zuul.routes.cr-mapping.url = http://192.168.101.60/cr-mapping/
zuul.routes.crp-routing.path = /base/or/v1/**
zuul.routes.crp-routing.url = http://192.168.101.60/crp-uat-route-or/
zuul.routes.drive-test.path = /drive-test/**
zuul.routes.drive-test.url = http://10.51.22.248:32188/
zuul.routes.event-23m.path = /routing-services-23/event/**
zuul.routes.event-23m.url = http://192.168.101.204:8094/event/
zuul.routes.event-23plus.path = /event-23plus/**
zuul.routes.event-23plus.url = http://192.168.101.204:8094/
zuul.routes.line-search-2023.path = /line_search_2023/**
zuul.routes.line-search-2023.url = http://192.168.101.130:19005/
zuul.routes.rgeo-service.path = /rgeo_service/**
zuul.routes.rgeo-service.url = http://10.50.210.249:8090/
zuul.routes.route-range-map-25m-uat.path = /routerangemap-25/**
zuul.routes.route-range-map-25m-uat.url = http://192.168.101.60/
zuul.routes.routing-services-25m-uat.path = /routing-services-25/**
zuul.routes.routing-services-25m-uat.url = http://192.168.101.60/
zuul.routes.routing-services-uat-25mm.path = /routing-services-25mm/**
zuul.routes.routing-services-uat-25mm.url = http://192.168.101.60/toyota23-uat/
zuul.routes.routing-services-uat.path = /routing-services-23/**
zuul.routes.routing-services-uat.url = http://192.168.101.60/toyota23-uat/
zuul.routes.search2021-uat.path = /search2021_2023/**
zuul.routes.search2021-uat.url = http://192.168.101.251:6001/
zuul.routes.search2022-uat.path = /search2022_2023/**
zuul.routes.search2022-uat.url = http://192.168.101.60/
zuul.routes.tmc-23m.path = /routing-services-23/tmc/**
zuul.routes.tmc-23m.url = http://192.168.101.204:8084/
zuul.routes.tmc-23plus.path = /tmc-23plus/**
zuul.routes.tmc-23plus.url = http://192.168.101.204:8084/
zuul.routes.topic-services-2023.path = /topic_search_2023/**
zuul.routes.topic-services-2023.url = http://192.168.101.130:27149/
zuul.routes.topic-services.path = /topic_search/**
zuul.routes.topic-services.url = http://192.168.101.130:27149/
zuul.semaphore.max-semaphores = 5000
zuul.sensitive-headers = 
zuul.SimpleHostRoutingFilter.route.disable = true
zuul.threadPool.useSeparateThreadPools = true
